[workspace]
authors = ["Wm Talcott <wtalcott@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
name = "mojo-addon-examples"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
max = ">=26.3.0.dev2026040905"
nodejs = ">=22.12"
